version: "3"

services:

  go:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      GOOS: linux
    env_file:
      - ./aws.env
    volumes:
      - ./:/go/src/github.com/silinternational/speed-snitch-agent
    working_dir: /go/src/github.com/silinternational/speed-snitch-agent
    command: ["bash"]

  rpm:
    build:
      context: ./docker/rpm
      dockerfile: Dockerfile
    volumes:
      - ./docker/rpm:/data
    working_dir: /data
    command: ["/data/run-rpm.sh"]

  fpm:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    volumes:
      - ./docker/fpm:/data
      - ./:/go/src/github.com/silinternational/speed-snitch-agent
    working_dir: /data
    env_file:
      - fpm.env
    command: ["/data/run-fpm.sh"]